name: fpslogapi

services:
  # MongoDB service
  mongodb:
    image: mongo
    ports:
      - "27017:27017"  # Map container port 27017 to host port 27017 (default for MongoDB)
    environment:
      MONGO_INITDB_DATABASE: fpslogdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/fpslogdb --quiet
      retries: 3
      timeout: 5s
    networks:
      - local
    volumes:
      - mongodb_config:/data/configdb
      - mongodb_data:/data/db

  # Spring Boot application service
  api:
    build: .  # Build the Spring application image from the current directory (Dockerfile)
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080
      - "5005:5005"
    environment:
      SPRING_APPLICATION_NAME: fpslogapi  # Set application name from application.properties
      # SPRING_DATA_MONGODB_HOST: mongodb
      # SPRING_DATA_MONGODB_PORT: 27017
      # SPRING_DATA_MONGODB_DATABASE: fpslogdb  # Set database name from application.properties
      SPRINGDOC_API_DOCS_PATH: /api-docs  # Set API docs path from application.properties
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html  # Set Swagger UI path from application.properties
    networks:
     - local
    depends_on:
      - mongodb

networks:
  local:
    driver: "bridge"
    name: ${NETWORK_NAME:-local}

volumes:
  mongodb_config:
  mongodb_data:  # Optional volume to persist MongoDB data (if used in MongoDB service)